name: timezone_utc_offset
description: Dart package for getting UTC offsets for timezones
version: 1.0.0
author: odam1
homepage: https://github.com/odam1/timezone_utc_offset.git

environment:
  sdk: ">=2.12.0 <3.0.0" 
