name: timezone_utc_offset
description: A Dart package for getting UTC offsets for timezones. This package is platform agnostic, thus can be used on all platforms that support dart code execution.
version: 1.1.0 
homepage: https://github.com/odam1/timezone_utc_offset.git

environment:
  sdk: ">=2.12.0 <3.0.0" 
